/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SlotService } from "../slot.service";
import { SlotCreateInput } from "./SlotCreateInput";
import { Slot } from "./Slot";
import { SlotFindManyArgs } from "./SlotFindManyArgs";
import { SlotWhereUniqueInput } from "./SlotWhereUniqueInput";
import { SlotUpdateInput } from "./SlotUpdateInput";
import { ReservationFindManyArgs } from "../../reservation/base/ReservationFindManyArgs";
import { Reservation } from "../../reservation/base/Reservation";
import { ReservationWhereUniqueInput } from "../../reservation/base/ReservationWhereUniqueInput";

export class SlotControllerBase {
  constructor(protected readonly service: SlotService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Slot })
  async createSlot(@common.Body() data: SlotCreateInput): Promise<Slot> {
    return await this.service.createSlot({
      data: data,
      select: {
        createdAt: true,
        endTime: true,
        id: true,
        isAvailable: true,
        startTime: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Slot] })
  @ApiNestedQuery(SlotFindManyArgs)
  async slots(@common.Req() request: Request): Promise<Slot[]> {
    const args = plainToClass(SlotFindManyArgs, request.query);
    return this.service.slots({
      ...args,
      select: {
        createdAt: true,
        endTime: true,
        id: true,
        isAvailable: true,
        startTime: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Slot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async slot(
    @common.Param() params: SlotWhereUniqueInput
  ): Promise<Slot | null> {
    const result = await this.service.slot({
      where: params,
      select: {
        createdAt: true,
        endTime: true,
        id: true,
        isAvailable: true,
        startTime: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Slot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSlot(
    @common.Param() params: SlotWhereUniqueInput,
    @common.Body() data: SlotUpdateInput
  ): Promise<Slot | null> {
    try {
      return await this.service.updateSlot({
        where: params,
        data: data,
        select: {
          createdAt: true,
          endTime: true,
          id: true,
          isAvailable: true,
          startTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Slot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSlot(
    @common.Param() params: SlotWhereUniqueInput
  ): Promise<Slot | null> {
    try {
      return await this.service.deleteSlot({
        where: params,
        select: {
          createdAt: true,
          endTime: true,
          id: true,
          isAvailable: true,
          startTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/reservations")
  @ApiNestedQuery(ReservationFindManyArgs)
  async findReservations(
    @common.Req() request: Request,
    @common.Param() params: SlotWhereUniqueInput
  ): Promise<Reservation[]> {
    const query = plainToClass(ReservationFindManyArgs, request.query);
    const results = await this.service.findReservations(params.id, {
      ...query,
      select: {
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        reservationDate: true,

        slot: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/reservations")
  async connectReservations(
    @common.Param() params: SlotWhereUniqueInput,
    @common.Body() body: ReservationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reservations: {
        connect: body,
      },
    };
    await this.service.updateSlot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/reservations")
  async updateReservations(
    @common.Param() params: SlotWhereUniqueInput,
    @common.Body() body: ReservationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reservations: {
        set: body,
      },
    };
    await this.service.updateSlot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/reservations")
  async disconnectReservations(
    @common.Param() params: SlotWhereUniqueInput,
    @common.Body() body: ReservationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reservations: {
        disconnect: body,
      },
    };
    await this.service.updateSlot({
      where: params,
      data,
      select: { id: true },
    });
  }
}
